# Generated by Django 2.1.3 on 2018-11-16 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpsHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=50, null=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('system', models.CharField(blank=True, max_length=50, null=True, verbose_name='主机系统')),
                ('manager', models.CharField(max_length=50, null=True, verbose_name='主机管理人员')),
                ('status', models.CharField(blank=True, choices=[('1', '使用中'), ('2', '未使用'), ('3', '故障'), ('4', '其它')], max_length=20, null=True, verbose_name='使用状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('mobity_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='OpsServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='系统名称(简)')),
                ('full_name', models.CharField(max_length=20, verbose_name='系统名称(全)')),
                ('number', models.CharField(max_length=10, verbose_name='系统编号')),
                ('lever', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=20, verbose_name='系统层级')),
                ('en_name', models.CharField(max_length=20, null=True, verbose_name='英文缩写')),
                ('platform', models.CharField(max_length=20, null=True, verbose_name='所属平台')),
                ('old_lever', models.CharField(max_length=20, null=True, verbose_name='系统级别(旧)')),
                ('new_lever', models.CharField(max_length=20, null=True, verbose_name='重要级别')),
                ('department', models.CharField(choices=[('yyglb', '运营管理部'), ('hlwjrb', '互联网金融部'), ('xxkfb', '信息开发部'), ('ersyb', 'E融事业部'), ('yhkb', '银行卡部'), ('gjyw', '国际业务部')], max_length=20, null=True, verbose_name='所属部门')),
                ('status', models.CharField(choices=[('1', '使用中'), ('2', '未使用'), ('3', '故障'), ('4', '其它')], max_length=20, verbose_name='系统状态')),
                ('ha_ip', models.GenericIPAddressField(verbose_name='HA地址')),
                ('manager', models.CharField(max_length=50, null=True, verbose_name='运营负责人')),
                ('dev_manager', models.CharField(max_length=50, null=True, verbose_name='运营负责人')),
                ('sale_manager', models.CharField(max_length=50, null=True, verbose_name='运营负责人')),
                ('vendor', models.CharField(max_length=50, null=True, verbose_name='开发商')),
                ('vendor_person', models.CharField(max_length=50, null=True, verbose_name='开发商联系人')),
                ('vendor_phone', models.CharField(max_length=50, null=True, verbose_name='开发商联系电话')),
                ('online_time', models.DateTimeField(null=True, verbose_name='投产时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('mobity_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
        ),
        migrations.AddField(
            model_name='opshost',
            name='ops_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.OpsServer'),
        ),
    ]
