# Generated by Django 2.1.3 on 2018-11-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsserver',
            name='dev_manager',
            field=models.CharField(max_length=50, null=True, verbose_name='开发负责人'),
        ),
        migrations.AlterField(
            model_name='opsserver',
            name='sale_manager',
            field=models.CharField(max_length=50, null=True, verbose_name='业务负责人'),
        ),
    ]
