# Generated by Django 2.1.3 on 2018-11-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20181116_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsserver',
            name='ha_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='HA地址'),
        ),
    ]
